/**
 * @file cssGenerator.ts
 * @description Compiles ElementEngineConfig into CSS custom properties and DOM rules
 */

import { ElementEngineConfig } from "./types";

/**
 * Generates dynamic CSS variables and style overrides for the dashboard.
 */
export function generateElementEngineCSS(config: ElementEngineConfig): string {
  const { global, header, groups, segments, buttons, drawers, matrixBg, customVars } = config;

  let customVarRules = "";
  if (customVars) {
    for (const [varName, varVal] of Object.entries(customVars)) {
      const formattedName = varName.startsWith("--") ? varName : `--${varName}`;
      customVarRules += `  ${formattedName}: ${varVal};\n`;
    }
  }

  return `
/* Generated by Element Engine Protocol v${config.meta.version} */
:root {
  /* Global Element Tokens */
  --element-radius-card: ${global.borderRadiusCard};
  --element-radius-btn: ${global.borderRadiusButton};
  --element-shadow: ${global.shadowIntensity};
  --element-blur: ${global.blurBackdrop};
  --element-accent-primary: ${global.primaryAccent};
  --element-accent-secondary: ${global.secondaryAccent};

  /* Header Element Tokens */
  --element-header-bg: ${header.background};
  --element-header-border: ${header.borderBottom};
  --element-header-clock: ${header.clockColor};
  --element-header-title: ${header.brandTitleColor};
  --element-header-voice-bg: ${header.voiceButtonBg};

  /* Groups Element Tokens */
  --element-group-bg: ${groups.cardBg};
  --element-group-border: ${groups.cardBorder};
  --element-group-title: ${groups.headerTitleColor};
  --element-group-badge-bg: ${groups.headerBadgeBg};
  --element-group-gap: ${groups.gapSpacing};

  /* Segments Element Tokens */
  --element-segment-active-bg: ${segments.activeCardBg};
  --element-segment-inactive-bg: ${segments.inactiveCardBg};
  --element-segment-active-border: ${segments.activeBorder};
  --element-segment-inactive-border: ${segments.inactiveBorder};
  --element-segment-active-glow: ${segments.activeGlow};
  --element-segment-icon-active: ${segments.iconActiveColor};
  --element-segment-icon-inactive: ${segments.iconInactiveColor};
  --element-segment-toggle-on: ${segments.toggleOnBg};
  --element-segment-toggle-off: ${segments.toggleOffBg};

  /* Button Tokens */
  --element-btn-primary-bg: ${buttons.primaryBg};
  --element-btn-primary-text: ${buttons.primaryText};
  --element-btn-secondary-bg: ${buttons.secondaryBg};
  --element-btn-secondary-text: ${buttons.secondaryText};
  --element-btn-danger-bg: ${buttons.dangerBg};
  --element-btn-hover-scale: ${buttons.hoverScale};

  /* Drawer Tokens */
  --element-drawer-bg: ${drawers.background};
  --element-drawer-header-bg: ${drawers.headerBg};
  --element-drawer-tab-active-bg: ${drawers.tabActiveBg};
  --element-drawer-tab-active-text: ${drawers.tabActiveText};
  --element-drawer-border: ${drawers.borderColor};

  /* Matrix Background Tokens */
  --element-matrix-color: ${matrixBg.color};
  --element-matrix-opacity: ${matrixBg.opacity};

${customVarRules}}

/* Element Engine Active Overrides */
.element-card {
  border-radius: var(--element-radius-card) !important;
  backdrop-filter: blur(var(--element-blur)) !important;
}

.element-btn {
  border-radius: var(--element-radius-btn) !important;
  transition: transform 0.2s ease, background-color 0.2s ease !important;
}

.element-btn:hover {
  transform: scale(var(--element-btn-hover-scale)) !important;
}
  `.trim();
}
