import { StateCreator } from "zustand";
import { IoTStoreState, AestheticSlice } from "../types";

export const createAestheticSlice: StateCreator<IoTStoreState, [], [], AestheticSlice> = (set) => ({
  isDark: false,
  accent3: "#D4AF37",
  accent4: "#10B981",
  selectedFont: "changa",
  animationsEnabled: true,
  animationsFps: 60,
  headerAnimationType: "fade",
  headerTitle: "سامانه هوشمند پادشاهی هخامنش",
  matrixDensity: 40,
  matrixSize: 4,
  matrixHoverSize: 3,
  matrixOpacity: 15,
  matrixColor: "#D4AF37",
  matrixMoving: true,
  matrixMouseEffect: true,
  matrixTwinkleEffect: false,
  matrixTwinkleSpeed: 50,
  headerPosition: "top",
  dashboardBgColor: "default",
  dashboardBgOpacity: 10,
  isSidebarCollapsed: false,
  dashboardWidth: 1,
  isGroupsCompactLayout: false,
  isSegmentsCompactLayout: false,

  setIsDark: (d) => set({ isDark: d }),
  setAccent3: (a) => set({ accent3: a }),
  setAccent4: (a) => set({ accent4: a }),
  setSelectedFont: (f) => set({ selectedFont: f }),
  setAnimationsEnabled: (e) => set({ animationsEnabled: e }),
  setAnimationsFps: (f) => set({ animationsFps: f }),
  setHeaderAnimationType: (t) => set({ headerAnimationType: t }),
  setHeaderTitle: (t) => set({ headerTitle: t }),
  setMatrixDensity: (d) => set({ matrixDensity: d }),
  setMatrixSize: (s) => set({ matrixSize: s }),
  setMatrixHoverSize: (s) => set({ matrixHoverSize: s }),
  setMatrixOpacity: (o) => set({ matrixOpacity: o }),
  setMatrixColor: (c) => set({ matrixColor: c }),
  setMatrixMoving: (m) => set({ matrixMoving: m }),
  setMatrixMouseEffect: (m) => set({ matrixMouseEffect: m }),
  setMatrixTwinkleEffect: (t) => set({ matrixTwinkleEffect: t }),
  setMatrixTwinkleSpeed: (s) => set({ matrixTwinkleSpeed: s }),
  setHeaderPosition: (p) => set({ headerPosition: p }),
  setDashboardBgColor: (c) => set({ dashboardBgColor: c }),
  setDashboardBgOpacity: (o) => set({ dashboardBgOpacity: o }),
  setIsSidebarCollapsed: (c) => set({ isSidebarCollapsed: c }),
  setDashboardWidth: (w) => set({ dashboardWidth: w }),
  setIsGroupsCompactLayout: (c) => set({ isGroupsCompactLayout: c }),
  setIsSegmentsCompactLayout: (c) => set({ isSegmentsCompactLayout: c }),
});
