import {
  Radio,
  Wifi,
  Palette,
  Type,
  Sparkles,
  LayoutGrid,
  Command,
  Mic,
  Settings2,
  Activity,
  Music,
} from "lucide-react";
import { SettingsGroupMeta, SettingsCategory } from "./types";

export const SETTINGS_GROUPS_META: Record<string, SettingsGroupMeta> = {
  mqtt: {
    id: "mqtt",
    title: "پروتکل MQTT و کارگزار (Broker)",
    subtitle: "تنظیمات اتصال، آدرس بروکر و سطح QoS",
    category: "network",
    categoryLabel: "ارتباطات",
    Icon: Radio,
  },
  wifi: {
    id: "wifi",
    title: "شبکه وای‌فای (Wi-Fi)",
    subtitle: "مدیریت شبکه و رمز عبور اتصال به برد",
    category: "network",
    categoryLabel: "ارتباطات",
    Icon: Wifi,
  },
  colors: {
    id: "colors",
    title: "رنگ‌ها و پالت‌های داشبورد",
    subtitle: "رنگ‌های اصلی، ثانویه و پریست‌های سنتی",
    category: "appearance",
    categoryLabel: "ظاهر",
    Icon: Palette,
  },
  fonts: {
    id: "fonts",
    title: "تایپوگرافی و فونت‌ها",
    subtitle: "انتخاب فونت‌های استاندارد و سلطنتی",
    category: "appearance",
    categoryLabel: "ظاهر",
    Icon: Type,
  },
  matrix: {
    id: "matrix",
    title: "پس‌زمینه و انیمیشن ماتریکس",
    subtitle: "تنظیم تراکم، رنگ و جلوه‌های ویژه ماتریکس",
    category: "appearance",
    categoryLabel: "ظاهر",
    Icon: Sparkles,
  },
  layout: {
    id: "layout",
    title: "چیدمان و نمای داشبورد",
    subtitle: "عرض داشبورد و حالت‌های فشرده‌سازی سگمنت‌ها",
    category: "layout",
    categoryLabel: "چیدمان",
    Icon: LayoutGrid,
  },
  "header-settings": {
    id: "header-settings",
    title: "تنظیمات هدر اصلی",
    subtitle: "موقعیت قرارگیری و عنوان هدر داشبورد",
    category: "layout",
    categoryLabel: "چیدمان",
    Icon: LayoutGrid,
  },
  macros: {
    id: "macros",
    title: "کلیدهای سفارشی (ماکروها)",
    subtitle: "تعریف سناریوها و دکمه‌های اجرای سریع",
    category: "automation",
    categoryLabel: "هوشمندی",
    Icon: Command,
  },
  "voice-commands": {
    id: "voice-commands",
    title: "دستورات دستیار صوتی",
    subtitle: "تعریف جملات فرمان صوتی و اکشن‌ها",
    category: "automation",
    categoryLabel: "هوشمندی",
    Icon: Mic,
  },
  conditions: {
    id: "conditions",
    title: "شرط‌ها و قوانین خودکار",
    subtitle: "قوانین شرطی کنترل پین‌ها و سگمنت‌ها",
    category: "automation",
    categoryLabel: "هوشمندی",
    Icon: Settings2,
  },
  animations: {
    id: "animations",
    title: "پایداری و انیمیشن‌ها",
    subtitle: "کنترل فریم‌ریت و حالت کم‌مصرف داده",
    category: "audio",
    categoryLabel: "کارایی",
    Icon: Activity,
  },
  audio: {
    id: "audio",
    title: "صدا و موزیک پس‌زمینه",
    subtitle: "مدیریت پخش‌کننده و افکت‌های صوتی",
    category: "audio",
    categoryLabel: "صدا",
    Icon: Music,
  },
};

export const CATEGORY_FILTERS: { id: SettingsCategory; label: string }[] = [
  { id: "all", label: "همه تنظیمات" },
  { id: "network", label: "ارتباطات و شبکه" },
  { id: "appearance", label: "تِم و ظاهر" },
  { id: "layout", label: "چیدمان و هدر" },
  { id: "automation", label: "هوشمندی و سناریو" },
  { id: "audio", label: "صدا و کارایی" },
];
